/*********************************************************************************************************************
 * Copyright (c) 2021, Infineon Technologies AG
 *
 *
 * Distributed under the Boost Software License, Version 1.0.
 *
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *********************************************************************************************************************/

/********************************************************************************************************
 * @file        TLE926x_SPI.c
 *
 * @brief       Implementation of all SPI related functions
 *
 * @version     V1.0.0
 * @date
 * @author      Fedy Farhat
 * @author      Michael Schaffarczyk
 ********************************************************************************************************/

/* ================================================================================ */
/* ============================   HEADER FILES     ================================ */
/* ================================================================================ */

#include <tle926x/TLE926x_SPI.h>

/* ================================================================================ */
/* =======================   SPI communication functions     ====================== */
/* ================================================================================ */

/*RDK4 Platform Global Variables*/
cyhal_spi_t rdk4_spi_obj;

/* Initialize the SPI Interface */
uint8_t sbc_spi_init(void)
{
	cy_rslt_t result = CY_RSLT_SUCCESS;

	/*SPI Initialization*/
	result = cyhal_spi_init(
			&RDK4_SPI_HANDLE,
			RDK4_SPI_MOSI,
			RDK4_SPI_MISO,
			RDK4_SPI_CLK,
			RDK4_SPI_CS,
			NULL,
			8,
			CYHAL_SPI_MODE_01_LSB,
			false);
    if(result != CY_RSLT_SUCCESS)
    {
  	  return 1;
    }

    result = cyhal_spi_set_frequency(&RDK4_SPI_HANDLE, RDK4_SPI_FREQ);
    if(result != CY_RSLT_SUCCESS)
    {
    	return 1;
    }

	return 0;
}

/*The SPI transfer function*/
uint16_t SBC_SPI_TRANSFER16(uint8_t Upper, uint8_t Lower)
{
	uint8_t spi_rx[2] = {0};
	uint8_t spi_tx[2];

	spi_tx[0] = Upper;
	spi_tx[1] = Lower;

	cyhal_spi_transfer(&RDK4_SPI_HANDLE, spi_tx, 2, spi_rx, 2, 0x00);

	return (uint16_t)(spi_rx[0]<<8 | spi_rx[1]);
}
